name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - uses: trmcnvn/chrome-addon@v2
        with:
          extension: dhadelkabablecjhglpdnjbigkcdfdlm
          zip: build/build.zip
          client-id: ${{ secrets.WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}